#Je v katalogu český popis?

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
ASK {
  [] a dcat:Catalog ;
    dcterms:description ?description .
    FILTER(langMatches(LANG(?description), "cs"))
}